# Generated by Django 6.0.5 on 2026-05-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(blank=True, help_text='Benefícios oferecidos'),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_type',
            field=models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('internship', 'Estágio'), ('freelance', 'Freelance'), ('temporary', 'Temporário')], default='clt', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, choices=[('none', 'Sem exigência'), ('high_school', 'Ensino Médio'), ('associate', 'Tecnólogo'), ('bachelors', 'Bacharelado'), ('masters', 'Mestrado'), ('phd', 'Doutorado')], default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='languages',
            field=models.CharField(blank=True, help_text='Idiomas requeridos', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, help_text="Cidade/Estado ou 'Remoto'", max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience_years',
            field=models.FloatField(default=0, help_text='Anos mínimos de experiência'),
        ),
        migrations.AddField(
            model_name='job',
            name='openings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='work_model',
            field=models.CharField(choices=[('onsite', 'Presencial'), ('remote', 'Remoto'), ('hybrid', 'Híbrido')], default='onsite', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='Descrição detalhada da vaga, responsabilidades, etc.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='nice_to_have',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='seniority',
            field=models.CharField(choices=[('apprentice', 'Jovem Aprendiz'), ('intern', 'Estágio'), ('trainee', 'Trainee'), ('junior', 'Júnior'), ('mid_level', 'Pleno'), ('senior', 'Sênior'), ('specialist', 'Especialista'), ('staff', 'Staff'), ('principal', 'Principal'), ('tech_lead', 'Tech Lead'), ('architect', 'Arquiteto'), ('coordinator', 'Coordenador(a)'), ('product_owner', 'Product Owner'), ('manager', 'Gerente'), ('head', 'Head'), ('director', 'Diretor(a)'), ('vp', 'VP'), ('c_level', 'C-Level (CTO/CIO/CPO)')], default='mid_level', max_length=20),
        ),
    ]
