# Generated by Django 6.0.5 on 2026-05-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_job_application_deadline_job_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status_detail',
            field=models.TextField(blank=True, default=''),
        ),
    ]
